# Generated by Django 3.0.5 on 2020-05-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200502_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='tipo_contrato',
            field=models.CharField(choices=[('CLT', 'Consolidação das Leis do Trabalho'), ('PJ', 'Pessoa Jurídica')], max_length=50),
        ),
    ]
