# Generated by Django 3.0.5 on 2020-05-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200502_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='tipo_contrato',
            field=models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('CLT', 'Consolidação das Leis do Trabalho')], max_length=50),
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_vaga', to='api.Vaga')),
            ],
            options={
                'db_table': 'requisito',
            },
        ),
    ]
